# Netlify build configuration for MandemOS Hecate Hydra

## The build section defines how Netlify should build the project.
## We use `npm install` here instead of `npm ci` because there is no
## package-lock.json in the repository. Running `npm install` will
## generate a lockfile during the build, preventing errors like
## `npm error code EUSAGE` that occur when `npm ci` is used without
## an existing lockfile.

[build]
  # For this project there is no compile step – it's a plain HTML/JS site.
  # We still run `npm install` so that Netlify will generate a lockfile
  # (required by `npm ci` if you later enable that) and to satisfy the
  # build command requirement. The build script defined in package.json
  # simply echoes a message and does nothing else.
  command = "npm install --no-audit --no-fund && npm run build"

  # The site files (index.html, script.js, style.css) live in the root
  # of the repository. Set the publish directory to "." so Netlify
  # serves these files directly.
  publish = "."

[build.environment]
  # Pin the Node.js version to match Netlify's default LTS version.
  NODE_VERSION = "18"
